// Pattern Generation Functions for WordPress Themes
// Based on Cruip/Neon design system

export function generateFunctionsPhp(functionPrefix: string, data: any): string {
  return `<?php
/**
 * ${data.businessName} Theme Functions
 * Generated by AnvilWP - https://anvilwp.com
 */

// Enqueue fonts
add_action('wp_enqueue_scripts', function() {
    wp_enqueue_style('${functionPrefix}-fonts',
        'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800;900&family=Inter:wght@300;400;500;600;700&display=swap',
        [],
        null
    );

    wp_enqueue_style('${functionPrefix}-theme',
        get_template_directory_uri() . '/assets/css/theme.css',
        [],
        '1.0.0'
    );

    wp_enqueue_script('${functionPrefix}-anvilwp',
        get_template_directory_uri() . '/assets/js/anvilwp.js',
        [],
        '1.0.0',
        true
    );
});

// Register pattern categories
add_action('init', function() {
    register_block_pattern_category('${functionPrefix}', [
        'label' => '${data.businessName}'
    ]);
});

// Remove WordPress bloat
remove_action('wp_head', 'print_emoji_detection_script', 7);
remove_action('wp_print_styles', 'print_emoji_styles');
remove_action('wp_head', 'wp_generator');
remove_action('wp_head', 'wlwmanifest_link');
remove_action('wp_head', 'rsd_link');

// Add SEO meta tags
add_action('wp_head', function() {
    if (is_front_page() || is_home()) {
        $site_name = get_bloginfo('name');
        $description = '${data.description || data.tagline}';
        $keywords = ${JSON.stringify(data.seo?.keywords || [])};

        echo '<meta name="description" content="' . esc_attr($description) . '">' . "\\n";
        echo '<meta name="keywords" content="' . esc_attr(implode(', ', $keywords)) . '">' . "\\n";

        // Open Graph
        echo '<meta property="og:title" content="' . esc_attr($site_name) . '">' . "\\n";
        echo '<meta property="og:description" content="' . esc_attr($description) . '">' . "\\n";
        echo '<meta property="og:type" content="website">' . "\\n";
        echo '<meta property="og:url" content="' . esc_url(home_url('/')) . '">' . "\\n";

        // Twitter Card
        echo '<meta name="twitter:card" content="summary_large_image">' . "\\n";
        echo '<meta name="twitter:title" content="' . esc_attr($site_name) . '">' . "\\n";
        echo '<meta name="twitter:description" content="' . esc_attr($description) . '">' . "\\n";
    }
}, 1);

// Add Schema.org JSON-LD
add_action('wp_footer', function() {
    if (is_front_page() || is_home()) {
        $schema = [
            '@context' => 'https://schema.org',
            '@type' => 'Organization',
            'name' => get_bloginfo('name'),
            'description' => '${data.description || data.tagline}',
            'url' => home_url('/'),
        ];
        echo '<script type="application/ld+json">' . wp_json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) . '</script>' . "\\n";
    }
});

// Contact Form API endpoint
add_action('rest_api_init', function() {
    register_rest_route('anvilwp/v1', '/contact', [
        'methods' => 'POST',
        'callback' => '${functionPrefix}_handle_contact_form',
        'permission_callback' => '__return_true'
    ]);
});

function ${functionPrefix}_handle_contact_form($request) {
    $params = $request->get_json_params();

    // Honeypot check
    if (!empty($params['website'])) {
        return new WP_Error('spam', 'Spam detected', ['status' => 400]);
    }

    $name = sanitize_text_field($params['name'] ?? '');
    $email = sanitize_email($params['email'] ?? '');
    $message = sanitize_textarea_field($params['message'] ?? '');

    if (empty($name) || empty($email) || empty($message)) {
        return new WP_Error('invalid', 'Todos los campos son requeridos', ['status' => 400]);
    }

    if (!is_email($email)) {
        return new WP_Error('invalid_email', 'Email inválido', ['status' => 400]);
    }

    $admin_email = get_option('admin_email');
    $subject = '${data.businessName} - Nuevo mensaje de contacto';
    $body = "Nombre: $name\\nEmail: $email\\n\\nMensaje:\\n$message";
    $headers = ['Content-Type: text/plain; charset=UTF-8'];

    $sent = wp_mail($admin_email, $subject, $body, $headers);

    if ($sent) {
        return rest_ensure_response([
            'success' => true,
            'message' => '¡Mensaje enviado! Te contactaremos pronto.'
        ]);
    } else {
        return new WP_Error('send_failed', 'Error al enviar el mensaje', ['status' => 500]);
    }
}
?>`
}

export function generateAdvancedCSS(data: any): string {
  const primary = data.colors?.primary || '#0A1E3D'
  const accent = data.colors?.accent || '#3B82F6'
  const secondary = data.colors?.secondary || '#8B5CF6'

  return `/* ${data.businessName} Theme Styles - AnvilWP Generated */

/* ============================================
   CSS CUSTOM PROPERTIES
   ============================================ */

:root {
  /* Colors */
  --c-bg-primary: #0d1117;
  --c-bg-secondary: #161b27;
  --c-bg-tertiary: #1e2535;
  --c-text-primary: #e2e8f0;
  --c-text-secondary: #94a3b8;
  --c-text-tertiary: #64748b;

  /* Brand Colors */
  --c-primary: ${primary};
  --c-accent: ${accent};
  --c-secondary: ${secondary};
  --c-success: #10B981;
  --c-warning: #F59E0B;
  --c-error: #EF4444;

  /* Spacing */
  --space-xs: 4px;
  --space-sm: 8px;
  --space-md: 16px;
  --space-lg: 24px;
  --space-xl: 32px;
  --space-2xl: 48px;
  --space-3xl: 64px;
  --space-4xl: 80px;
  --space-5xl: 120px;

  /* Border Radius */
  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --radius-xl: 16px;
  --radius-2xl: 24px;
  --radius-full: 9999px;

  /* Shadows */
  --shadow-sm: 0 4px 6px rgba(0, 0, 0, 0.1);
  --shadow-md: 0 10px 15px rgba(0, 0, 0, 0.1);
  --shadow-lg: 0 20px 25px rgba(0, 0, 0, 0.15);
  --shadow-xl: 0 25px 50px rgba(0, 0, 0, 0.25);
  --shadow-blue: 0 10px 40px rgba(59, 130, 246, 0.3);
  --shadow-glow: 0 0 40px rgba(59, 130, 246, 0.2);

  /* Transitions */
  --transition-fast: 150ms ease-in-out;
  --transition-base: 200ms ease-in-out;
  --transition-slow: 300ms ease-in-out;
}

/* ============================================
   BASE STYLES
   ============================================ */

body {
  background: var(--c-bg-primary);
  color: var(--c-text-primary);
  font-family: 'Inter', sans-serif;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

h1, h2, h3, h4, h5, h6 {
  font-family: 'Plus Jakarta Sans', sans-serif;
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.01em;
}

a {
  color: var(--c-accent);
  text-decoration: none;
  transition: var(--transition-fast);
}

a:hover {
  color: var(--c-secondary);
}

/* ============================================
   HERO SECTION
   ============================================ */

.anvilwp-hero {
  padding-top: 120px;
  padding-bottom: 80px;
  text-align: center;
  position: relative;
  overflow: hidden;
  background: var(--c-bg-primary);
}

/* Radial glow effect */
.anvilwp-hero::before {
  content: '';
  position: absolute;
  top: -50%;
  left: 50%;
  transform: translateX(-50%);
  width: 800px;
  height: 300px;
  background: radial-gradient(
    ellipse,
    rgba(59, 130, 246, 0.15) 0%,
    rgba(139, 92, 246, 0.1) 40%,
    transparent 70%
  );
  z-index: 0;
  pointer-events: none;
}

.anvilwp-hero-content {
  position: relative;
  z-index: 1;
  max-width: 800px;
  margin: 0 auto;
}

/* Badge */
.anvilwp-badge {
  display: inline-block;
  padding: 8px 16px;
  background: var(--c-bg-secondary);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: var(--radius-full);
  font-size: 0.875rem;
  margin-bottom: 24px;
  color: var(--c-text-secondary);
}

/* Gradient text */
.anvilwp-gradient-text {
  background: linear-gradient(135deg, var(--c-accent), var(--c-secondary));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  display: inline-block;
}

/* ============================================
   CARDS & COMPONENTS
   ============================================ */

.anvilwp-card {
  background: var(--c-bg-tertiary);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: var(--radius-xl);
  padding: 32px;
  transition: all var(--transition-slow);
}

.anvilwp-card:hover {
  transform: translateY(-4px);
  border-color: rgba(59, 130, 246, 0.3);
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.4);
}

/* Feature cards */
.anvilwp-feature-card {
  text-align: center;
}

.anvilwp-feature-icon {
  font-size: 3rem;
  line-height: 1;
  margin-bottom: 16px;
  display: inline-block;
}

/* Stats */
.anvilwp-stat-value {
  font-family: 'Plus Jakarta Sans', sans-serif;
  font-size: clamp(2.5rem, 4vw, 3.5rem);
  font-weight: 800;
  background: linear-gradient(135deg, var(--c-accent), var(--c-secondary));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  line-height: 1;
  margin-bottom: 8px;
}

.anvilwp-stat-label {
  color: var(--c-text-secondary);
  font-size: 0.875rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

/* Testimonials */
.anvilwp-testimonial {
  background: var(--c-bg-secondary);
  border-radius: var(--radius-lg);
  padding: 24px;
  display: flex;
  flex-direction: column;
  height: 100%;
}

.anvilwp-testimonial-quote {
  color: var(--c-text-secondary);
  font-size: 1rem;
  line-height: 1.6;
  margin-bottom: 16px;
  flex: 1;
}

.anvilwp-testimonial-quote::before {
  content: '"';
  font-size: 2rem;
  color: var(--c-accent);
  opacity: 0.3;
  line-height: 0;
  display: block;
  margin-bottom: 8px;
}

.anvilwp-testimonial-author {
  display: flex;
  align-items: center;
  gap: 12px;
}

.anvilwp-testimonial-avatar {
  width: 48px;
  height: 48px;
  border-radius: var(--radius-full);
  background: var(--c-bg-tertiary);
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  color: var(--c-accent);
}

.anvilwp-testimonial-name {
  color: var(--c-text-primary);
  font-weight: 600;
  margin-bottom: 4px;
}

.anvilwp-testimonial-role {
  color: var(--c-text-tertiary);
  font-size: 0.875rem;
}

/* ============================================
   BUTTONS
   ============================================ */

.anvilwp-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 14px 28px;
  border-radius: var(--radius-md);
  font-weight: 600;
  font-size: 1rem;
  transition: var(--transition-fast);
  cursor: pointer;
  border: none;
  text-decoration: none;
}

.anvilwp-button-primary {
  background: linear-gradient(to top, #2563EB, var(--c-accent));
  color: white;
  box-shadow: var(--shadow-blue);
}

.anvilwp-button-primary:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 50px rgba(59, 130, 246, 0.4);
  color: white;
}

.anvilwp-button-secondary {
  background: var(--c-bg-secondary);
  color: var(--c-text-primary);
  border: 1px solid rgba(255, 255, 255, 0.1);
}

.anvilwp-button-secondary:hover {
  background: var(--c-bg-tertiary);
  border-color: rgba(59, 130, 246, 0.3);
}

/* Button arrow animation */
.anvilwp-button-arrow {
  display: inline-block;
  margin-left: 8px;
  transition: var(--transition-fast);
}

.anvilwp-button:hover .anvilwp-button-arrow {
  transform: translateX(4px);
}

/* ============================================
   CTA SECTION
   ============================================ */

.anvilwp-cta {
  background: linear-gradient(135deg, var(--c-accent) 0%, var(--c-secondary) 100%);
  border-radius: var(--radius-lg);
  padding: clamp(40px, 8vw, 80px) clamp(24px, 6vw, 60px);
  text-align: center;
  position: relative;
  overflow: hidden;
}

.anvilwp-cta::before {
  content: '';
  position: absolute;
  top: -50%;
  right: -20%;
  width: 500px;
  height: 500px;
  background: radial-gradient(circle, rgba(255, 255, 255, 0.1) 0%, transparent 70%);
  pointer-events: none;
}

.anvilwp-cta-title {
  color: white;
  margin-bottom: 16px;
}

.anvilwp-cta-subtitle {
  color: rgba(255, 255, 255, 0.9);
  font-size: 1.125rem;
  margin-bottom: 32px;
}

/* ============================================
   SECTIONS
   ============================================ */

.anvilwp-section {
  padding-top: 80px;
  padding-bottom: 80px;
}

.anvilwp-section-header {
  text-align: center;
  margin-bottom: 60px;
  max-width: 700px;
  margin-left: auto;
  margin-right: auto;
}

.anvilwp-section-title {
  font-size: clamp(2rem, 4vw, 3rem);
  margin-bottom: 16px;
}

.anvilwp-section-subtitle {
  color: var(--c-text-secondary);
  font-size: 1.125rem;
}

/* ============================================
   GRID LAYOUTS
   ============================================ */

.anvilwp-grid-2 {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 24px;
}

.anvilwp-grid-3 {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 32px;
}

/* ============================================
   ANIMATIONS
   ============================================ */

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.anvilwp-fade-in {
  animation: fadeIn 0.6s ease-out;
}

/* ============================================
   RESPONSIVE
   ============================================ */

@media (max-width: 900px) {
  .anvilwp-hero {
    padding-top: 80px;
    padding-bottom: 60px;
  }

  .anvilwp-section {
    padding-top: 60px;
    padding-bottom: 60px;
  }

  .anvilwp-grid-3 {
    grid-template-columns: 1fr;
    gap: 24px;
  }

  .anvilwp-stat-value {
    font-size: 2.5rem;
  }
}

@media (max-width: 600px) {
  .anvilwp-hero {
    padding-top: 60px;
    padding-bottom: 40px;
  }

  .anvilwp-section {
    padding-top: 40px;
    padding-bottom: 40px;
  }

  .anvilwp-card {
    padding: 24px;
  }

  .anvilwp-button {
    width: 100%;
  }
}

/* ============================================
   UTILITY CLASSES
   ============================================ */

.anvilwp-text-center {
  text-align: center;
}

.anvilwp-text-muted {
  color: var(--c-text-secondary);
}

.anvilwp-mb-sm { margin-bottom: var(--space-sm); }
.anvilwp-mb-md { margin-bottom: var(--space-md); }
.anvilwp-mb-lg { margin-bottom: var(--space-lg); }
.anvilwp-mb-xl { margin-bottom: var(--space-xl); }
.anvilwp-mb-2xl { margin-bottom: var(--space-2xl); }

.anvilwp-mt-sm { margin-top: var(--space-sm); }
.anvilwp-mt-md { margin-top: var(--space-md); }
.anvilwp-mt-lg { margin-top: var(--space-lg); }
.anvilwp-mt-xl { margin-top: var(--space-xl); }
.anvilwp-mt-2xl { margin-top: var(--space-2xl); }`
}

export function generateHeroPattern(themeSlug: string, data: any): string {
  const hero = data.hero || {}
  const badge = hero.badge || ''
  const title = hero.title || data.businessName
  const titleAccent = hero.titleAccent || data.tagline
  const subtitle = hero.subtitle || data.description || ''
  const ctaPrimary = hero.cta?.primary || 'Comenzar'
  const ctaSecondary = hero.cta?.secondary || ''

  return `<?php
/**
 * Title: Hero Principal
 * Slug: ${themeSlug}/hero
 * Categories: ${themeSlug}
 * Description: Hero section con radial glow y gradient text
 */
?>
<!-- wp:group {"align":"full","className":"anvilwp-hero","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull anvilwp-hero has-global-padding is-layout-constrained wp-block-group-is-layout-constrained">

<!-- wp:group {"className":"anvilwp-hero-content","layout":{"type":"constrained","contentSize":"800px"}} -->
<div class="wp-block-group anvilwp-hero-content is-layout-constrained wp-block-group-is-layout-constrained">

${badge ? `<!-- wp:paragraph {"align":"center","className":"anvilwp-badge"} -->
<p class="has-text-align-center anvilwp-badge">✨ ${badge}</p>
<!-- /wp:paragraph -->

` : ''}<!-- wp:heading {"textAlign":"center","level":1,"style":{"typography":{"fontSize":"clamp(2.5rem,5vw,5rem)","lineHeight":"1.2"}}} -->
<h1 class="wp-block-heading has-text-align-center" style="font-size:clamp(2.5rem,5vw,5rem);line-height:1.2">${title}<br><span class="anvilwp-gradient-text">${titleAccent}</span></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"var(--c-text-secondary)"},"typography":{"fontSize":"1.25rem"}}} -->
<p class="has-text-align-center" style="color:var(--c-text-secondary);font-size:1.25rem">${subtitle}</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"},"style":{"spacing":{"margin":{"top":"40px"}}}} -->
<div class="wp-block-buttons is-layout-flex wp-block-buttons-is-layout-flex" style="margin-top:40px">
<!-- wp:button {"backgroundColor":"accent","className":"anvilwp-button anvilwp-button-primary"} -->
<div class="wp-block-button anvilwp-button anvilwp-button-primary"><a class="wp-block-button__link has-accent-background-color has-background wp-element-button">${ctaPrimary} <span class="anvilwp-button-arrow">→</span></a></div>
<!-- /wp:button -->
${ctaSecondary ? `
<!-- wp:button {"className":"anvilwp-button anvilwp-button-secondary"} -->
<div class="wp-block-button anvilwp-button anvilwp-button-secondary"><a class="wp-block-button__link wp-element-button">${ctaSecondary}</a></div>
<!-- /wp:button -->` : ''}
</div>
<!-- /wp:buttons -->

</div>
<!-- /wp:group -->

</div>
<!-- /wp:group -->`
}

// Continue with more pattern generators...
// (Due to length, I'll create these in separate files)
